apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deployment-name>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <app-name>
  template:
    metadata:
      labels:
        app: <app-name>
    spec:
      containers:
        - name: <container-name>
          image: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/poc_eks_airflow:latest
          ports:
            - containerPort: 80
